[project]
name = "mydemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-groq>=1.1.0",
    "langchain-openai>=1.1.0",
    "mcp-use>=1.5.0",
]
